<?php

namespace Projet2\BackBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeRepository extends EntityRepository
{
    /*public function getProductsbyType(){
        $query = $this->createQueryBuilder('a')
        // On joint sur l'attribut type
        ->leftJoin('a.product', 'p')
        ->addSelect('p')
        // On joint sur l'attribut categories
        ->leftJoin('p.categories', 'c')
        ->addSelect('c')
        ->orderBy('a.type', 'ASC')
        ->getQuery();
        
        return $query->getResult();
    }*/
}
